version: '3.8'

services:
  backend:
    build: ./backend
    container_name: sse-backend
    restart: 'on-failure'
    environment:
      - MONGODB_URI=mongodb+srv://zildirayalfirli:Zildiray123@warningsystem.eextqwr.mongodb.net/?retryWrites=true&w=majority&appName=WarningSystem
      - PORT=9000
    ports:
      - "9000:9000"

  frontend:
    build: ./frontend
    container_name: sse-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: sse-backend-cadvisor
    restart: always
    ports:
      - "8181:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
    devices:
      - /dev/kmsg:/dev/kmsg
    depends_on:
      - backend

  prometheus:
    image: prom/prometheus:latest
    container_name: sse-backend-prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:latest
    container_name: sse-backend-grafana
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/data:/var/lib/grafana
    user: "0"
    depends_on:
      - prometheus
    ports:
      - "3000:3000"

# volumes:
#   grafana_data:
