{
 "title": "SSE Container Monitoring",
 "description": "This dashboard uses cAdvisor exporter to show docker container key metrics. ",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "docker_host",
    "label": "Docker Host",
    "query": {
     "query": "label_values({__name__=~\"container.*\"},instance)"
    }
   },
   {
    "name": "container_name",
    "label": "Container Name",
    "query": {
     "query": "label_values({__name__=~\"container.*\", instance=~\"$docker_host\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Host Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Core usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Cores" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{instance=~\"$docker_host\",name=~\".+\"}[$__rate_interval])) by(instance) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Memory Usage by Host",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{instance=~\"$docker_host\",name=~\".+\"}) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CPU Usage (% by Core) Container",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_cpu_usage_seconds_total{instance=~\"$docker_host\", name=\"sse-backend\"}[$__rate_interval])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Memory Usage Container",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(name) (container_memory_usage_bytes{instance=~\"$docker_host\", name=~\"$container_name\", name=\"sse-backend\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Received Network Traffic",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{instance=~\"$docker_host\",name=~\"$container_name\",name=~\".+\"}[$__rate_interval])) by (name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sent Network Traffic",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{instance=~\"$docker_host\",name=~\"$container_name\",name=~\".+\"}[$__rate_interval])) by (name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Usage (% by Core) Gauge",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(name) (rate(container_cpu_usage_seconds_total{instance=~\"$docker_host\", name=\"sse-backend\"}[$__rate_interval])) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage Stat",
     "type": "stat",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(name) (container_memory_usage_bytes{instance=~\"$docker_host\", name=~\"$container_name\", name=\"sse-backend\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}